#pragma once

void initIO();
void configureSensors();
void readSensors();
void sendSensorData();
void showLedFeedback();
void showLedAssistance();
void sendAndReceiveBLEData();
void BLEconfig();
void sendBLEData();
void getBLEData();
void saveConfigurationToFlash();
void readConfigurationFromFlash();
void updateConfigurationChar();
void updateStatistics();
void calculateOptimalRange();
void powerOffFunctionality();
void sleepToSavePower();
void isBatteryOk();
void showLedAllSensorsInRange();
void showLedAnySensorInRange();
void showLedAnySensorInRangeTwoColors();
void showLedAllSensorsInRangeWithOverpressureColor();
void disableUART();